# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errchkjson
    - errname
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errchkjson:
      check-error-free-encoding: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    lll:
      line-length: 120
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: _test\.go
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/nutanix-cloud-native)
        - localmodule
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
