prism_central:
  endpoint: "prismcentral.sts2-cluster.internal.nutanix-dev.devcluster.openshift.com"
  port: "9440"
  insecure: true

vm_filters:
  name_prefixes:
    - "ci-op-"
  category_pattern: "kubernetes-io-cluster-"

thresholds:
  orphan_ttl_hours: 8
