prism_central:
  endpoint: "prismcentral.sts2-cluster.internal.nutanix-dev.devcluster.openshift.com"
  port: "9440"
  insecure: true

vm_filters:
  name_prefixes:
    - "ci-op-"

thresholds:
  orphan_ttl_hours: 8

capacity_monitoring:
  cluster_uuids:
    - "000648c3-465d-9bfe-b452-4941f7a3457a"
  thresholds:
    cpu_warning_percent: 70
    cpu_critical_percent: 85
    memory_warning_percent: 70
    memory_critical_percent: 85
